import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ContainerPage } from "@/components/Container/ContainerPage";
import { Header } from "@/components/Header/Header";
import { ThemeProvider } from "@/contexts/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Testando DarkMode com Context e Persistência",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <ThemeProvider>
        <ContainerPage>
        <Header/>
          {children}
        </ContainerPage>
        </ThemeProvider>
      </body>
    </html>
  );
}
